// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: jobs.proto

package jobs_server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Jobs_AddJob_FullMethodName = "/Jobs/AddJob"
)

// JobsClient is the client API for Jobs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobsClient interface {
	AddJob(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[JobData, PendingJob], error)
}

type jobsClient struct {
	cc grpc.ClientConnInterface
}

func NewJobsClient(cc grpc.ClientConnInterface) JobsClient {
	return &jobsClient{cc}
}

func (c *jobsClient) AddJob(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[JobData, PendingJob], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Jobs_ServiceDesc.Streams[0], Jobs_AddJob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[JobData, PendingJob]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Jobs_AddJobClient = grpc.ClientStreamingClient[JobData, PendingJob]

// JobsServer is the server API for Jobs service.
// All implementations must embed UnimplementedJobsServer
// for forward compatibility.
type JobsServer interface {
	AddJob(grpc.ClientStreamingServer[JobData, PendingJob]) error
	mustEmbedUnimplementedJobsServer()
}

// UnimplementedJobsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobsServer struct{}

func (UnimplementedJobsServer) AddJob(grpc.ClientStreamingServer[JobData, PendingJob]) error {
	return status.Errorf(codes.Unimplemented, "method AddJob not implemented")
}
func (UnimplementedJobsServer) mustEmbedUnimplementedJobsServer() {}
func (UnimplementedJobsServer) testEmbeddedByValue()              {}

// UnsafeJobsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobsServer will
// result in compilation errors.
type UnsafeJobsServer interface {
	mustEmbedUnimplementedJobsServer()
}

func RegisterJobsServer(s grpc.ServiceRegistrar, srv JobsServer) {
	// If the following call pancis, it indicates UnimplementedJobsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Jobs_ServiceDesc, srv)
}

func _Jobs_AddJob_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(JobsServer).AddJob(&grpc.GenericServerStream[JobData, PendingJob]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Jobs_AddJobServer = grpc.ClientStreamingServer[JobData, PendingJob]

// Jobs_ServiceDesc is the grpc.ServiceDesc for Jobs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Jobs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Jobs",
	HandlerType: (*JobsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AddJob",
			Handler:       _Jobs_AddJob_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "jobs.proto",
}
