services:
    proxy:
        container_name: proxy
        build:
            context: ./proxy/
            dockerfile: Dockerfile
        depends_on:
            - api
            - jobs-server
        ports:
            - '8080:8080'
            - '443:443'
        volumes:
            - logs:/logs
        restart: always
        networks:
            qnet:
                ipv4_address: 172.18.0.30

    db:
        container_name: postgres-db
        hostname: postgresInstance
        build:
            context: ./server/database/
            dockerfile: Dockerfile
        env_file:
            - ./postgres.env
            - ./db.env
        ports:
            - '5432:5432'
        volumes:
            # https://stackoverflow.com/questions/41637505/how-to-persist-data-in-a-dockerized-postgres-database-using-volumes
            - data:/var/lib/postgresql/data
            - postgres:/var/run/postgresql
            - logs:/var/log
            - qasm:/qasm
        restart: always
        networks:
            - qnet

    queue-handler:
        container_name: rabbitmq
        hostname: rabbitmqInstance
        image: rabbitmq:4.0.5-alpine
        restart: always
        ports:
            - '5672:5672'
            - '15672:15672'
        networks:
            qnet: {}
    jobs-server:
        container_name: jobs-server
        hostname: jobsServerInstance
        build:
            context: ./server/
            dockerfile: jobsServer.Dockerfile
        ports:
            - '50051:50051'
        depends_on:
            - db
            - queue-handler
        env_file:
            - ./db.env
            - ./rabbitmq.env
        environment:
            HOST: 0.0.0.0
            PORT: 50051
            QASM_PATH: /qasm
        restart: always
        volumes:
            - qasm:/qasm
        networks:
            qnet: {}

    workers:
        build:
            context: ./server/worker/
            dockerfile: Dockerfile
        depends_on:
            - db
            - queue-handler
            - jobs-server
        deploy:
            mode: replicated
            replicas: 4
        restart: always
        env_file:
            - ./rabbitmq.env
            - ./db.env
        volumes:
            - qasm:/qasm
        networks:
            qnet: {}

    api:
        container_name: api
        hostname: apiInstance
        build:
            context: ./server/
            dockerfile: restAPI.Dockerfile
        depends_on:
            - db
        ports:
            - '3000:3000'
        env_file:
            - ./db.env
        environment:
            GIN_MODE: release
            PORT: 3000
        restart: always
        networks:
            qnet: {}

volumes:
    data:
        external: false
    postgres:
        external: false
    qasm:
        external: false
    logs:
        external: false

networks:
    qnet:
        external: false
        #https://stackoverflow.com/questions/27937185/assign-static-ip-to-docker-container
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/27 # 30 usable IPs
                  ip_range: 172.18.0.0/27
                  gateway: 172.18.0.1
