services:
    db:
        container_name: postgres-db
        hostname: postgresInstance #https://stackoverflow.com/questions/29924843/how-do-i-set-hostname-in-docker-compose
        build:
            context: ./server/database/
            dockerfile: Dockerfile
        restart: always
        environment:
            POSTGRES_PASSWORD: test
            POSTGRES_USER: test
        ports:
            - '5432:5432'
        volumes:
            # https://stackoverflow.com/questions/41637505/how-to-persist-data-in-a-dockerized-postgres-database-using-volumes
            - data:/var/lib/postgresql/data
            - postgres:/var/run/postgresql
            - qasm:/qasm
    queue-handler:
        container_name: rabbitmq
        hostname: rabbitmqInstance
        image: rabbitmq:4.0.5-alpine
        restart: always
        ports:
            - '5672:5672'
            - '15672:15672'

    jobs-server:
        container_name: jobs-server
        build:
            context: ./server/jobsServer/
            dockerfile: Dockerfile
        ports:
            - '50051:50051'
        depends_on:
            - db
            - queue-handler
        environment:
            HOST: 0.0.0.0
            PORT: 50051
            RABBITMQ_HOST: rabbitmqInstance
            RABBITMQ_PORT: 5672
            RABBITMQ_QUEUE_NAME: qexec
            DB_HOST: postgresInstance
            DB_PORT: 5432
            DB_USERNAME: test
            DB_PASSWORD: test
            DB_NAME: quantum
            QASM_PATH: /qasm
        restart: always
        volumes:
            - qasm:/qasm

    workers:
        build:
            context: ./server/worker
            dockerfile: Dockerfile
        depends_on:
            - db
            - queue-handler
            - jobs-server
        deploy:
            mode: replicated
            replicas: 4
        restart: always
        environment:
            RABBITMQ_HOST: rabbitmqInstance
            RABBITMQ_PORT: 5672
            RABBITMQ_QUEUE_NAME: qexec
            DB_HOST: postgresInstance
            DB_PORT: 5432
            DB_NAME: quantum
            DB_USER: test
            DB_PASSWORD: test
        volumes:
            - qasm:/qasm

volumes:
    data:
        external: false
    postgres:
        external: false
    qasm:
        external: false
