services:
    proxy:
        container_name: proxy
        image: ghcr.io/dpbm/qproxy
        depends_on:
            - api
            - jobs-server
        ports:
            - '8080:8080'
            - '443:443'
        volumes:
            - logs:/logs
        restart: always
        networks:
            qnet:
                ipv4_address: 172.18.0.30

    db:
        container_name: postgres-db
        hostname: postgresInstance
        image: ghcr.io/dpbm/qdb
        env_file:
            - ./db.env
            - ./postgres.env
        ports:
            - '5432:5432'
        volumes:
            - data:/var/lib/postgresql/data
            - postgres:/var/run/postgresql
            - logs:/var/log
            - qasm:/qasm
        restart: always
        networks:
            - qnet

    queue-handler:
        container_name: rabbitmq
        hostname: rabbitmqInstance
        image: rabbitmq:4.0.5-alpine
        healthcheck:
            test: rabbitmq-diagnostics check_port_connectivity
            interval: 5s
            timeout: 10s
            retries: 3
        env_file:
            - ./rabbitmq.env
        restart: always
        ports:
            - '5672:5672'
            - '15672:15672'
        networks:
            - qnet

    jobs-server:
        container_name: jobs-server
        hostname: jobsServerInstance
        image: ghcr.io/dpbm/qjobsserver
        ports:
            - '50051:50051'
        depends_on:
            - db
            - queue-handler
        env_file:
            - ./db.env
            - ./queue.env
        environment:
            HOST: 172.18.0.29
            PORT: 50051
            QASM_PATH: /qasm
            LOG_FILE_PATH: /logs/jobs-server/logs.log
        restart: always
        volumes:
            - qasm:/qasm
            - logs:/logs
        networks:
            qnet:
                ipv4_address: 172.18.0.29

    api:
        container_name: api
        hostname: apiInstance
        image: ghcr.io/dpbm/qapi
        depends_on:
            - db
        ports:
            - '3000:3000'
        env_file:
            - ./db.env
        environment:
            GIN_MODE: release
            PORT: 3000
            LOG_FILE_PATH: /logs/api/logs.log
            TRUSTED_PROXY: 172.18.0.30 # only incoming requests from the proxy can be accepted
        restart: always
        volumes:
            - logs:/logs
        networks:
            qnet:
                ipv4_address: 172.18.0.28

    workers:
        image: ghcr.io/dpbm/qworker
        depends_on:
            - jobs-server
        deploy:
            mode: replicated
            replicas: 4 # you can add up to 25 replicas
        env_file:
            - ./queue.env
            - ./db.env
        environment:
            LOGS_PATH: /logs/worker/
        restart: always
        volumes:
            - qasm:/qasm
            - logs:/logs
        networks:
            - qnet

volumes:
    data:
        external: false
    postgres:
        external: false
    qasm:
        external: false
    logs:
        external: false

networks:
    qnet:
        external: false
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/27 # 30 usable IPs
                  ip_range: 172.18.0.0/27
                  gateway: 172.18.0.1
