#!/bin/bash

export JOBS_SERVER_HOST=localhost
export JOBS_SERVER_PORT=50051

export JOBS_SERVER_RABBITMQ_HOST=rabbitmqInstance
export JOBS_SERVER_RABBITMQ_PORT=5672

export JOBS_SERVER_POSTGRES_HOST=postgresInstance
export JOBS_SERVER_POSTGRES_PORT=5432
export JOBS_SERVER_POSTGRES_USERNAME=test
export JOBS_SERVER_POSTGRES_PASSWORD=test


QASM_PATH=./qasm
export JOBS_SERVER_QASM_PATH=$QASM_PATH

mkdir -p $QASM_PATH

go run server/server.go