name: worker
channels:
    - conda-forge
dependencies:
    - pip
    - python=3.12
    - pip:
          - pika
          - psycopg2-binary
          - tox
          - black
          - pylint
          - mypy
          - types-psycopg2
          - pytest
