requires = ["tox>=4"]
env_list = ["lint", "types", "py3.12", "py3.11", "py3.10"]

[env.lint]
description = "lint code"
skip_install = false
deps = ["black", "pylint"]
commands = [["black", { replace = "posargs", default = ["."], extend = true} ], ["pylint",  { replace = "posargs", default = ["."], extend = true}]]

[env.types]
description = "check types"
skip_install = false
deps = ["mypy", "types-psycopg2"]
commands = [["mypy", { replace = "posargs", default = [".", "--exclude", ".tox"], extend = true} ]]
