name: (Reusable Workflow) Test production docker compose files
on:
  workflow_call:
    inputs:
      file:
        description: "the compose file path"
        required: true
        type: string

jobs:
    test-compose-file:
        name: Test compose file on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-24.04
                    - ubuntu-24.04-arm

        steps:
            - uses: actions/checkout@v4

            - name: run compose
              uses: nick-fields/retry@v3
              with:
                  timeout_minutes: 30
                  retry_wait_seconds: 120
                  max_attempts: 3
                  command: DB_USERNAME=test DB_PASSWORD=test DB_ROOT_USER=root DB_ROOT_PASSWORD=toor RABBITMQ_USER=test RABBITMQ_PASSWORD=test DOMAIN=test.com docker compose -f ${{ inputs.file }} up -d