name: Release
on:
    push:
        tags:
            - '*'


jobs:
    release:
        runs-on: ubuntu-24.04
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v3

            - name: create release
              uses: ncipollo/release-action@v1

    
    push_proxy:
        permissions:
            packages: write
            contents: read
            attestations: write
            id-token: write

        uses: ./.github/workflows/dockerhub-publish.yml
        secrets: 
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            DOCKERHUB_NAMESPACE: ${{ secrets.DOCKERHUB_NAMESPACE }}
        with:
            image_name: 'qproxy'
            context: './proxy'