name: Test parts

on: [push]

jobs:
    api:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v4

            - name: Setup Go 1.23.5
              uses: actions/setup-go@v5
              with:
                  go-version: '1.23.5'

            - name: Run tests
              run: |
                  cd ./server/restAPI &&
                  go mod download && 
                  go mod verify &&
                  go test ./test
