name: Test parts

on: [push]

jobs:
    api:
        runs-on: ubuntu-24.04

        steps:
            - uses: actions/checkout@v4

            - name: Setup Go 1.23.5
              uses: actions/setup-go@v5
              with:
                  go-version: '1.23.5'

            - name: setup
              working-directory: ./app
              run: |
                  go mod download && 
                  go mod verify

            - name: build
              working-directory: ./app
              run: go build

            - name: Run tests
              working-directory: ./app
              run: go test ./test
